version: '3.8'

services:
  web:
    build: .
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

    db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d


volumes:
  db_data:
