services:
  web:
    build: .
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:9.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: cwdoMUGHlyZErKtaOnELEWhTSAMJmtFc
      MYSQL_DATABASE: railway
      MYSQL_USER: root
      MYSQL_PASSWORD: cwdoMUGHlyZErKtaOnELEWhTSAMJmtFc
    ports:
      - "3306:3306"
      - "39974"
    volumes:
      - db_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
